#define DIO_u8PA0MODE     DIO_u8Impedance
#define DIO_u8PA1MODE     DIO_u8PULLUP
#define DIO_u8PA2MODE     DIO_u8High
#define DIO_u8PA3MODE     DIO_u8High
#define DIO_u8PA4MODE     DIO_u8High
#define DIO_u8PA5MODE     DIO_u8High
#define DIO_u8PA6MODE     DIO_u8High
#define DIO_u8PA7MODE     DIO_u8High
#define DIO_u8PB0MODE     DIO_u8High
#define DIO_u8PB1MODE     DIO_u8High
#define DIO_u8PB2MODE     DIO_u8High
#define DIO_u8PB3MODE     DIO_u8High
#define DIO_u8PB4MODE     DIO_u8High
#define DIO_u8PB5MODE     DIO_u8High
#define DIO_u8PB6MODE     DIO_u8High
#define DIO_u8PB7MODE     DIO_u8High
#define DIO_u8PC0MODE     DIO_u8High
#define DIO_u8PC1MODE     DIO_u8High
#define DIO_u8PC2MODE     DIO_u8High
#define DIO_u8PC3MODE     DIO_u8High
#define DIO_u8PC4MODE     DIO_u8High
#define DIO_u8PC5MODE     DIO_u8High
#define DIO_u8PC7MODE     DIO_u8High
#define DIO_u8PD0MODE     DIO_u8High
#define DIO_u8PD1MODE     DIO_u8High
#define DIO_u8PD2MODE     DIO_u8High
#define DIO_u8PD3MODE     DIO_u8High
#define DIO_u8PD4MODE     DIO_u8High
#define DIO_u8PD5MODE     DIO_u8High
#define DIO_u8PD6MODE     DIO_u8High
#define DIO_u8PD7MODE     DIO_u8High
